// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserVo.proto

package com.yilan.vo;

public final class UserVoProto {
  private UserVoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserVoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.UserVo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <code>optional string openId = 2;</code>
     */
    String getOpenId();
    /**
     * <code>optional string openId = 2;</code>
     */
    com.google.protobuf.ByteString
        getOpenIdBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string cellPhone = 4;</code>
     */
    String getCellPhone();
    /**
     * <code>optional string cellPhone = 4;</code>
     */
    com.google.protobuf.ByteString
        getCellPhoneBytes();

    /**
     * <code>optional string address = 5;</code>
     */
    String getAddress();
    /**
     * <code>optional string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>optional string createTime = 6;</code>
     */
    String getCreateTime();
    /**
     * <code>optional string createTime = 6;</code>
     */
    com.google.protobuf.ByteString
        getCreateTimeBytes();

    /**
     * <code>optional string updateTime = 7;</code>
     */
    String getUpdateTime();
    /**
     * <code>optional string updateTime = 7;</code>
     */
    com.google.protobuf.ByteString
        getUpdateTimeBytes();

    /**
     * <code>optional string stt = 8;</code>
     */
    String getStt();
    /**
     * <code>optional string stt = 8;</code>
     */
    com.google.protobuf.ByteString
        getSttBytes();
  }
  /**
   * <pre>
   *定义规范：
   *message类 均首字母大写   大写！！！！
   * </pre>
   *
   * Protobuf type {@code tutorial.UserVo}
   */
  public  static final class UserVo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.UserVo)
      UserVoOrBuilder {
    // Use UserVo.newBuilder() to construct.
    private UserVo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserVo() {
      userId_ = 0;
      openId_ = "";
      name_ = "";
      cellPhone_ = "";
      address_ = "";
      createTime_ = "";
      updateTime_ = "";
      stt_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserVo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              openId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              cellPhone_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              createTime_ = s;
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              updateTime_ = s;
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              stt_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserVoProto.internal_static_tutorial_UserVo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserVoProto.internal_static_tutorial_UserVo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserVo.class, Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int OPENID_FIELD_NUMBER = 2;
    private volatile Object openId_;
    /**
     * <code>optional string openId = 2;</code>
     */
    public String getOpenId() {
      Object ref = openId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        openId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string openId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOpenIdBytes() {
      Object ref = openId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        openId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELLPHONE_FIELD_NUMBER = 4;
    private volatile Object cellPhone_;
    /**
     * <code>optional string cellPhone = 4;</code>
     */
    public String getCellPhone() {
      Object ref = cellPhone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cellPhone_ = s;
        return s;
      }
    }
    /**
     * <code>optional string cellPhone = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCellPhoneBytes() {
      Object ref = cellPhone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cellPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile Object address_;
    /**
     * <code>optional string address = 5;</code>
     */
    public String getAddress() {
      Object ref = address_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>optional string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private volatile Object createTime_;
    /**
     * <code>optional string createTime = 6;</code>
     */
    public String getCreateTime() {
      Object ref = createTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string createTime = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCreateTimeBytes() {
      Object ref = createTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATETIME_FIELD_NUMBER = 7;
    private volatile Object updateTime_;
    /**
     * <code>optional string updateTime = 7;</code>
     */
    public String getUpdateTime() {
      Object ref = updateTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string updateTime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateTimeBytes() {
      Object ref = updateTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STT_FIELD_NUMBER = 8;
    private volatile Object stt_;
    /**
     * <code>optional string stt = 8;</code>
     */
    public String getStt() {
      Object ref = stt_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stt_ = s;
        return s;
      }
    }
    /**
     * <code>optional string stt = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSttBytes() {
      Object ref = stt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (!getOpenIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, openId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getCellPhoneBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cellPhone_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, updateTime_);
      }
      if (!getSttBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, stt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (!getOpenIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, openId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getCellPhoneBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cellPhone_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      if (!getCreateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, updateTime_);
      }
      if (!getSttBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, stt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserVo)) {
        return super.equals(obj);
      }
      UserVo other = (UserVo) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getOpenId()
          .equals(other.getOpenId());
      result = result && getName()
          .equals(other.getName());
      result = result && getCellPhone()
          .equals(other.getCellPhone());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && getCreateTime()
          .equals(other.getCreateTime());
      result = result && getUpdateTime()
          .equals(other.getUpdateTime());
      result = result && getStt()
          .equals(other.getStt());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + OPENID_FIELD_NUMBER;
      hash = (53 * hash) + getOpenId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CELLPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getCellPhone().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
      hash = (37 * hash) + STT_FIELD_NUMBER;
      hash = (53 * hash) + getStt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserVo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserVo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserVo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserVo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserVo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserVo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserVo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserVo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserVo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserVo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserVo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义规范：
     *message类 均首字母大写   大写！！！！
     * </pre>
     *
     * Protobuf type {@code tutorial.UserVo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.UserVo)
        UserVoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserVoProto.internal_static_tutorial_UserVo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserVoProto.internal_static_tutorial_UserVo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserVo.class, Builder.class);
      }

      // Construct using com.yilan.vo.UserVoProto.UserVo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0;

        openId_ = "";

        name_ = "";

        cellPhone_ = "";

        address_ = "";

        createTime_ = "";

        updateTime_ = "";

        stt_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserVoProto.internal_static_tutorial_UserVo_descriptor;
      }

      public UserVo getDefaultInstanceForType() {
        return UserVo.getDefaultInstance();
      }

      public UserVo build() {
        UserVo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UserVo buildPartial() {
        UserVo result = new UserVo(this);
        result.userId_ = userId_;
        result.openId_ = openId_;
        result.name_ = name_;
        result.cellPhone_ = cellPhone_;
        result.address_ = address_;
        result.createTime_ = createTime_;
        result.updateTime_ = updateTime_;
        result.stt_ = stt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserVo) {
          return mergeFrom((UserVo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserVo other) {
        if (other == UserVo.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getOpenId().isEmpty()) {
          openId_ = other.openId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getCellPhone().isEmpty()) {
          cellPhone_ = other.cellPhone_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getCreateTime().isEmpty()) {
          createTime_ = other.createTime_;
          onChanged();
        }
        if (!other.getUpdateTime().isEmpty()) {
          updateTime_ = other.updateTime_;
          onChanged();
        }
        if (!other.getStt().isEmpty()) {
          stt_ = other.stt_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserVo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserVo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int userId_ ;
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private Object openId_ = "";
      /**
       * <code>optional string openId = 2;</code>
       */
      public String getOpenId() {
        Object ref = openId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          openId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string openId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOpenIdBytes() {
        Object ref = openId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          openId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string openId = 2;</code>
       */
      public Builder setOpenId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        openId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string openId = 2;</code>
       */
      public Builder clearOpenId() {
        
        openId_ = getDefaultInstance().getOpenId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string openId = 2;</code>
       */
      public Builder setOpenIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        openId_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object cellPhone_ = "";
      /**
       * <code>optional string cellPhone = 4;</code>
       */
      public String getCellPhone() {
        Object ref = cellPhone_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cellPhone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string cellPhone = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCellPhoneBytes() {
        Object ref = cellPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cellPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cellPhone = 4;</code>
       */
      public Builder setCellPhone(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cellPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cellPhone = 4;</code>
       */
      public Builder clearCellPhone() {
        
        cellPhone_ = getDefaultInstance().getCellPhone();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cellPhone = 4;</code>
       */
      public Builder setCellPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cellPhone_ = value;
        onChanged();
        return this;
      }

      private Object address_ = "";
      /**
       * <code>optional string address = 5;</code>
       */
      public String getAddress() {
        Object ref = address_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddress(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private Object createTime_ = "";
      /**
       * <code>optional string createTime = 6;</code>
       */
      public String getCreateTime() {
        Object ref = createTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          createTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string createTime = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCreateTimeBytes() {
        Object ref = createTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          createTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string createTime = 6;</code>
       */
      public Builder setCreateTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string createTime = 6;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = getDefaultInstance().getCreateTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string createTime = 6;</code>
       */
      public Builder setCreateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createTime_ = value;
        onChanged();
        return this;
      }

      private Object updateTime_ = "";
      /**
       * <code>optional string updateTime = 7;</code>
       */
      public String getUpdateTime() {
        Object ref = updateTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string updateTime = 7;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateTimeBytes() {
        Object ref = updateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          updateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string updateTime = 7;</code>
       */
      public Builder setUpdateTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateTime = 7;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string updateTime = 7;</code>
       */
      public Builder setUpdateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateTime_ = value;
        onChanged();
        return this;
      }

      private Object stt_ = "";
      /**
       * <code>optional string stt = 8;</code>
       */
      public String getStt() {
        Object ref = stt_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          stt_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string stt = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSttBytes() {
        Object ref = stt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          stt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stt = 8;</code>
       */
      public Builder setStt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stt = 8;</code>
       */
      public Builder clearStt() {
        
        stt_ = getDefaultInstance().getStt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stt = 8;</code>
       */
      public Builder setSttBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stt_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.UserVo)
    }

    // @@protoc_insertion_point(class_scope:tutorial.UserVo)
    private static final UserVo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserVo();
    }

    public static UserVo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserVo>
        PARSER = new com.google.protobuf.AbstractParser<UserVo>() {
      public UserVo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserVo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserVo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserVo> getParserForType() {
      return PARSER;
    }

    public UserVo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_UserVo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_UserVo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014UserVo.proto\022\010tutorial\"\217\001\n\006UserVo\022\016\n\006u" +
      "serId\030\001 \001(\005\022\016\n\006openId\030\002 \001(\t\022\014\n\004name\030\003 \001(" +
      "\t\022\021\n\tcellPhone\030\004 \001(\t\022\017\n\007address\030\005 \001(\t\022\022\n" +
      "\ncreateTime\030\006 \001(\t\022\022\n\nupdateTime\030\007 \001(\t\022\013\n" +
      "\003stt\030\010 \001(\tB\033\n\014com.yilan.voB\013UserVoProtob" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_UserVo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_UserVo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_UserVo_descriptor,
        new String[] { "UserId", "OpenId", "Name", "CellPhone", "Address", "CreateTime", "UpdateTime", "Stt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
